version: "3.9"
services:

  postgres:
    build:
      context: .
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my-db
    networks:
      - my-network
    ports:
      - '5438:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  my_data: {}
